/*
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the AnnotatedSQL Wrapper Plugin library.
 */
package ${pkgName};

import android.content.ContentValues;

abstract class AbstractContentValues {

    protected ContentValues mContentValues = new ContentValues();

    public AbstractContentValues() {
        mContentValues = new ContentValues();
    }

    public ContentValues getContentValues() {
        return mContentValues;
    }

    public void clear() {
        mContentValues.clear();
    }
}