/*
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the AnnotatedSQL Wrapper Plugin library.
 */
package ${pkgName};

import ${tablePackage}.${storeName}.${tableName};

public class ${name} extends AbstractContentValues {

    public ${name}() {
        super();
    }

    <#list column as col>
        <#switch col.type>
        <#case 'INTEGER'>
    public ${name} put${col.baseName}(int value) {
        return put${col.baseName}(Integer.valueOf(value));
    }

    public ${name} put${col.baseName}(Integer value) {
        mContentValues.put(${col.expr}, value);
        return this;
    }

    public ${name} put${col.baseName}(long value) {
        return put${col.baseName}(Long.valueOf(value));
    }

    public ${name} put${col.baseName}(Long value) {
        mContentValues.put(${col.expr}, value);
        return this;
    }
        <#break>
        <#case 'REAL'>
    public ${name} put${col.baseName}(float value) {
        return put${col.baseName}(Float.valueOf(value));
    }

    public ${name} put${col.baseName}(Float value) {
        mContentValues.put(${col.expr}, value);
        return this;
    }

    public ${name} put${col.baseName}(double value) {
        return put${col.baseName}(Double.valueOf(value));
    }

    public ${name} put${col.baseName}(Double value) {
        mContentValues.put(${col.expr}, value);
        return this;
    }
        <#break>
        <#case 'BLOB'>
    public ${name} put${col.baseName}(byte[] value) {
        return put${col.baseName}(value);
    }
        <#break>
        <#default>
    public ${name} put${col.baseName}(CharSequence value) {
        mContentValues.put(${col.expr}, value);
        return this;
    }
        </#switch>
    </#list>
}