/*
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the AnnotatedSQL Wrapper Plugin library.
 */
package ${pkgName};

import ${tablePackage}.${storeName}.${tableName};

public class ${name} extends AbstractContentValues {

    public ${name}() {
        super();
    }

    <#list column as col>
    public ${name} put${col.baseName}(String value) {
        mContentValues.put(${col.expr}, value);
        return this;
    }
    </#list>
}